name: Codacy Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '45 13 * * 3'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d28ce580f19309cd493628eba4641f745822082c
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          output: results.sarif
          format: sarif
          verbose: true
          max-allowed-issues: 2147483647
          tool-options: >
            --tool trivy
            --gh-code-scanning-compat

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
